import type { Metadata } from "next";
import { font_inter, font_playwrite } from "@libs/configs/fonts";
import "./globals.css";
import { Toaster } from "@/components/molecules/Sonner/Sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font_inter.variable} ${font_playwrite.variable}`}>
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
